Initial
biocatchltd/heksher-py pull request #1
Opened 2021-01-27 15:13 UTC by bentheiii

2021-01-27 16:27 UTC, aviramha commented on LICENSE
> +Copyright (c) 2021, ben avrahami <ben.avrahami@biocatch.com>
Biocatch *

2021-01-28 09:02 UTC, bentheiii commented on LICENSE
> +Copyright (c) 2021, ben avrahami <ben.avrahami@biocatch.com>
drat foiled again

2021-01-28 10:33 UTC, aviramha commented on doc/source/conf.py
> +copyright = '2021, ben avrahami <ben.avrahami@biocatch.com>'
biocatch

2021-01-28 10:33 UTC, aviramha commented on pyproject.toml
> +orjson = "^3.4.6"
asd

2021-01-28 10:33 UTC, aviramha commented on pyproject.toml
> +orjson = "^3.4.6"
v

2021-01-28 11:13 UTC, aviramha requested changes

2021-01-28 11:13 UTC, aviramha commented on heksher/heksher_client.py
> +        if heksher.main_client.Main is not self:
I think Handover should support only getting a temproary client, as it's not like you can transfer between heksher clients

2021-01-28 11:13 UTC, aviramha commented on heksher/heksher_client.py
> +    def add_undeclared(self, settings: Collection[Setting]):
add_undeclared sounds odd, why not add_setting?

2021-01-28 11:13 UTC, aviramha commented on heksher/heksher_client.py
> +    def context_namespace(self, ns: Mapping[str, str]) -> Mapping[str, str]:
ns -> Namespace, don't be cheap

2021-01-28 11:13 UTC, aviramha commented on heksher/clients/subclasses.py
> +        return None
no need to return None

2021-01-28 11:32 UTC, omerhazan commented on heksher/heksher_client.py
> +    def handover_main(self, other: BaseHeksherClient):
When will the client use this? in which scenario?

2021-01-28 11:41 UTC, bentheiii commented on heksher/clients/subclasses.py
> +            logger.warning('some setting entries were changed by declaration',
Because it might be desired and might not

2021-02-02 12:33 UTC, omerhazan approved these changes

2021-02-04 02:22 UTC, bharel requested changes
I'm around halfway through

2021-02-04 08:35 UTC, bentheiii commented on heksher/clients/async_client.py
> +            logger.info('heksher reload done', extra={'updated_settings': list(updated_settings.keys())})
I don't think this is correct. If a setting changed between line 100 and 105, I want to get it in the next loop. I'd rather get the same update twice than miss an update.

2021-02-04 08:37 UTC, bentheiii commented on heksher/clients/async_client.py
> +                             extra={'service_url': self._service_url})
We actually want to continue by design, we want the services to keep going even if the keksher server is unavailable.

2021-02-04 08:58 UTC, aviramha commented on heksher/clients/async_client.py
> +                             extra={'service_url': self._service_url})
I agree with Ben, I'd just add that's it's worth to expose this to the consumer. I suggest adding an "alive" attribute or something, that is False if last communication attempt resulted in an error.

2021-02-04 10:29 UTC, aviramha commented on pyproject.toml
>  [tool.poetry.dependencies]
we probably need to be way more liberal on the dependencies versions, as we don't want to restrict users. 
I'd set it for same major as minimum

2021-02-04 10:37 UTC, bharel commented on heksher/clients/async_client.py
> +            logger.info('heksher reload done', extra={'updated_settings': list(updated_settings.keys())})
That's right. In the current scenario you miss an update.

2021-02-04 10:38 UTC, bharel commented on heksher/clients/async_client.py
> +                             extra={'service_url': self._service_url})
So we want services to continue going even if we have the wrong configuration? That doesn't sound right...

2021-02-04 11:49 UTC, bentheiii commented on heksher/clients/async_client.py
> +                             extra={'service_url': self._service_url})
We do have a `ping` method for the clients, they can use that to check connectivity.
As for restoration, I think just restarting the service would be good enough for now. We can probably put it up as an issue to be handled later.

2021-02-10 14:14 UTC, merged