ready for CR
biocatchltd/heksher-py pull request #22
Opened 2022-01-06 12:35 UTC by bentheiii

2022-01-09 14:21 UTC, omerhazan requested changes

2022-01-09 16:10 UTC, bentheiii commented on heksher/clients/stub.py
> +            self.setting.last_ruleset = value.value
The last_ruleset stores the ruleset the setting should work with, by replacing it, we tell the setting to return to its previous behaviour.

2022-01-09 16:11 UTC, bentheiii commented on heksher/clients/subclasses.py
> +            logger.error('conflict when declaring setting', extra={'setting_name': setting.name,
This log only appears on upgrade conflicts. i.e. if you're trying to declare a new or existing version in an incompatible way

2022-01-09 16:12 UTC, bentheiii commented on heksher/clients/subclasses.py
> +                logger.warning('unexpected response from service', extra={'response_content': response.content})
It might be valid for future versions IDK

2022-01-09 16:13 UTC, bentheiii commented on heksher/clients/subclasses.py
> +                logger.warning('setting default value discarded default due to conversion error', exc_info=True,
so that we know why the value was rejected (it might have been a validator)

2022-01-10 14:29 UTC, omerhazan approved these changes

2022-01-10 14:29 UTC, merged